version: '3'

services:
  cosmoapp:
    depends_on:
      - db
    build: 
      context: .
      dockerfile: Dockerfile
    image: cosmoapp-docker
    container_name: cosmoapp
    restart: always # Restart the container if it stops
    ports:
      - "${PORT}:${PORT}"
    environment:
      MONGODB: ${MONGODB}
      PORT: ${PORT}
      DEFAULT_LIMIT: ${DEFAULT_LIMIT}


  db:
    image: mongo:5
    container_name: mongo-cosmo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGODB_DATABASE: cosmo-gql